### PR TITLE
Porting Bootstrap templates

### PR DESCRIPTION
**Pull request by tarvos21**
### Using the framework

- [x] https://getbootstrap.com/examples/starter-template/
- [x] https://getbootstrap.com/examples/theme/
- [x] https://getbootstrap.com/examples/grid/
- [x] https://getbootstrap.com/examples/jumbotron/
- [x] https://getbootstrap.com/examples/jumbotron-narrow/

### Navbars in action
- [x] https://getbootstrap.com/examples/navbar/
- [x] https://getbootstrap.com/examples/navbar-static-top/
- [x] https://getbootstrap.com/examples/navbar-fixed-top/

### Custom components
- [x] https://getbootstrap.com/examples/cover/
- [x] https://getbootstrap.com/examples/carousel/
- [x] https://getbootstrap.com/examples/blog/
- [x] https://getbootstrap.com/examples/dashboard/
- [x] https://getbootstrap.com/examples/signin/
- [x] https://getbootstrap.com/examples/justified-nav/
- [x] https://getbootstrap.com/examples/sticky-footer/
- [x] https://getbootstrap.com/examples/sticky-footer-navbar/

### Experiments
- [x] https://getbootstrap.com/examples/non-responsive/
- [x] https://getbootstrap.com/examples/offcanvas/

### CODE REVIEW

**Comment by xiaohanyu** [comment]
It seems that Semantic-UI still lacks a Carousel component: https://github.com/Semantic-Org/Semantic-UI/issues/962. 

So if you have trouble implementing https://getbootstrap.com/examples/carousel/, just ignore it this time.

**Comment by tarvos21** [comment]
Oh, yes, indeed I got some trouble, 🤣. I have tried to make a simple carousel or slide like that, with some CSS and jQuery, almost usable, not perfect though, I will push it tomorrow.

**Comment by xiaohanyu** [comment]
Just saw your "Blog" template, it looks good, maybe we can use that layout for our own blog module   in http://semantic-ui-forest.com

**Comment by tarvos21** [comment]
OK, that's great, so I add this template to the blog home page?

**Comment by xiaohanyu** [comment]
Ah, no need to do that right now, we'll return to blog module after I come back.

**Comment by tarvos21** [comment]
Good

**Comment by xiaohanyu** [comment]
Many many thanks! Really awesome work!

**Pull request merged**
